language: generic
os: linux

cache:
  directories:
    - $HOME/texlive
    - $HOME/.texlive
    - $HOME/texmf

env:
  - EMACS_VERSION=25.1
  - EMACS_VERSION=25.2
  - EMACS_VERSION=25.3
  - EMACS_VERSION=26.1
  - EMACS_VERSION=26.2
  - EMACS_VERSION=26.3
  - EMACS_VERSION=27.1
  - EMACS_VERSION=master

jobs:
  allow_failures:
    - env: EMACS_VERSION=master

before_install:
  - wget https://raw.githubusercontent.com/y-yu/install-tex-travis/master/install-tex.sh
  - wget https://raw.githubusercontent.com/y-yu/install-tex-travis/master/tlmgr.sh
  - chmod +x install-tex.sh tlmgr.sh

install:
  - . ./install-tex.sh
  - ./tlmgr.sh install cluttex
  - curl -LO https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
  - tar -xaf emacs-bin-${EMACS_VERSION}.tar.gz -C /
  - export PATH=/tmp/emacs/bin:${PATH}
  - curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/travis-eldev > x.sh && source ./x.sh

script:
  - eldev -dtT lint
  - eldev -p -dtT test --expect 6
  - eldev -dtT compile --warnings-as-errors

